### ISSUE TITLE
Last item can be selected with loop=false

### ISSUE THREAD

**Issue by sobuctb** [anovi/selectonic#11]
Last item can be selected with loop=false and preventInputs=false when up arrow key pressed and no item in focus.

**Comment by anovi** [comment]
Hi there. loop=false option doesn't mean you can't select last item by up-arrow key. It just prevents looping.

There may be different opinions on this. For example Finder app in Mac OS selects last file in a folder if there is no focus on the list. Others may not.

You could prevent selecting last item by up-arrow if you check focus existence:
```javascript
/* in options object*/
before: function( event, ui ) {
  if (event.keyCode === 38 && !ui.focus) {
    this.selectonic('cancel');
  }
},
```

**Comment by sobuctb** [comment]
It helps, thank you. 

In my case plugin used with infinite scrolling, and it should be prevented because new data is added when plugin selects last item.
