### ISSUE TITLE
'_checkIfSelector' and '_checkIfElem' return null that isn't expected in 'select'

### ISSUE THREAD

**Issue by sobuctb** [anovi/selectonic#12]
I use text input to filter data in selectonic. I call 'refresh', 'unselect' and 'select' after each change in input to select first item in list:
```javascript
$element = $(element);
$element.selectonic('refresh');
$element.selectonic('unselect');
var filter = $element.selectonic("option", "filter"); // '.list_item'
setTimeout(function () { $element.selectonic('select', filter + ":first"); }, 10);		
```
Last line threw 'Uncaught TypeError: Cannot read property 'addClass' of null' if no item in list becouse '_checkIfSelector' and '_checkIfElem' return null.

P.S. Maybe it usefull to add 'selectFirst' option when calling 'refresh'?

**Comment by anovi** [comment]
Fixed a bug when 'select' method throws an error if is called on empty list.

Added possibility to select items by numbers. In your case it would be:
```javascript
$element.selectonic('refresh');
$element.selectonic('unselect');
setTimeout(function () {
  $element.selectonic('select', 0);
  $element.selectonic('focus', 0); 
}, 10);
```
Grab this version https://github.com/anovi/selectonic/releases/tag/v0.6.2

**Comment by sobuctb** [comment]
```if (selector && $.isNumeric(selector))``` is always false if ```selector === 0```

**Comment by anovi** [comment]
My apologies. Fixed — https://github.com/anovi/selectonic/releases/tag/v0.6.3
